collections:
# Has directory /_topics
  topics:
    # To output pages for each topic
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"

domain: terxor.github.io
url: https://terxor.github.io
